language: php
php:
  - 7.0
services:
  - docker
before_script:
  - docker pull elasticsearch:2.3
  - docker run -d -p 127.0.0.1:9200:9200 -v "$(pwd)/elasticsearch.yml":/usr/share/elasticsearch/config/elasticsearch.yml elasticsearch
  - sleep 15
